<a href="https://colab.research.google.com/github/Pheol9166/AIstudy/blob/main/ML/logistic_regression.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

### Logistic regression
: 이중 분류 문제 해결 시 사용되는 지도학습

#### sklearn 라이브러리를 통한 logistic regression 구현

In [ ]:
!pip install kaggle

In [ ]:
from google.colab import files
files.upload()

Saving kaggle.json to kaggle.json


{'kaggle.json': b'{"username":"phanol","key":"9fcb4d00706470462d7343f4defe5922"}'}

In [ ]:
!mkdir -p ~/.kaggle
!cp kaggle.json ~/.kaggle/

!chmod 600 ~/.kaggle/kaggle.json

In [21]:
# 데이터 준비 - fake bills
!kaggle datasets download -d alexandrepetit881234/fake-bills
!unzip fake-bills.zip

  0% 0.00/17.1k [00:00<?, ?B/s]
100% 17.1k/17.1k [00:00<00:00, 20.6MB/s]
Archive:  fake-bills.zip
  inflating: fake_bills.csv          


In [22]:
import pandas as pd
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.metrics import confusion_matrix
from sklearn.metrics import accuracy_score
from sklearn.metrics import precision_recall_fscore_support

In [23]:
# 가짜 돈 판별에 영향을 주는 것들
data = pd.read_csv("./fake_bills.csv", sep=";")
data

is_genuine  diagonal  height_left  height_right  margin_low  margin_up  \
0           True    171.81       104.86        104.95        4.52       2.89   
1           True    171.46       103.36        103.66        3.77       2.99   
2           True    172.69       104.48        103.50        4.40       2.94   
3           True    171.36       103.91        103.94        3.62       3.01   
4           True    171.73       104.28        103.46        4.04       3.48   
...          ...       ...          ...           ...         ...        ...   
1495       False    171.75       104.38        104.17        4.42       3.09   
1496       False    172.19       104.63        104.44        5.27       3.37   
1497       False    171.80       104.01        104.12        5.51       3.36   
1498       False    172.06       104.28        104.06        5.17       3.46   
1499       False    171.47       104.15        103.82        4.63       3.37   

      length  
0     112.83  
1     113.09  
2     113.16  
3     113.51  
4     112.54  
...      ...  
1495  111.28  
1496  110.97  
1497  111.95  
1498  112.25  
1499  112.07  

[1500 rows x 7 columns]

In [24]:
print(data.isna().sum())
len(data)

is_genuine       0
diagonal         0
height_left      0
height_right     0
margin_low      37
margin_up        0
length           0
dtype: int64


1500

In [25]:
data.dropna(inplace=True)

In [26]:
target = data['is_genuine']
data.drop(["is_genuine"], axis=1, inplace=True)

In [27]:
data

diagonal  height_left  height_right  margin_low  margin_up  length
0       171.81       104.86        104.95        4.52       2.89  112.83
1       171.46       103.36        103.66        3.77       2.99  113.09
2       172.69       104.48        103.50        4.40       2.94  113.16
3       171.36       103.91        103.94        3.62       3.01  113.51
4       171.73       104.28        103.46        4.04       3.48  112.54
...        ...          ...           ...         ...        ...     ...
1495    171.75       104.38        104.17        4.42       3.09  111.28
1496    172.19       104.63        104.44        5.27       3.37  110.97
1497    171.80       104.01        104.12        5.51       3.36  111.95
1498    172.06       104.28        104.06        5.17       3.46  112.25
1499    171.47       104.15        103.82        4.63       3.37  112.07

[1463 rows x 6 columns]

In [28]:
X_train, X_test, y_train, y_test = train_test_split(data, target, random_state=42)

In [29]:
# 정규화
scaler = StandardScaler()

X_train = scaler.fit_transform(X_train)
X_test = scaler.fit_transform(X_test)

In [30]:
len(X_train), len(X_test)

(1097, 366)

In [31]:
lr = LogisticRegression()
lr.fit(X_train, y_train)

LogisticRegression()

In [32]:
y_pred = lr.predict(X_test)
y_pred

array([False,  True,  True,  True,  True,  True, False,  True,  True,
        True, False,  True,  True,  True, False,  True,  True,  True,
        True, False,  True, False, False,  True,  True,  True,  True,
        True, False,  True, False,  True,  True,  True,  True,  True,
        True, False, False,  True,  True,  True, False,  True, False,
        True, False, False,  True, False,  True,  True,  True,  True,
        True,  True,  True,  True,  True, False,  True, False,  True,
        True, False,  True,  True, False, False,  True, False,  True,
       False,  True,  True,  True,  True,  True,  True,  True, False,
       False,  True, False, False, False,  True,  True,  True,  True,
       False,  True, False, False,  True,  True, False,  True, False,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
       False, False,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True, False,  True,  True, False, False, False,
       False, False,

In [33]:
print(data.columns)
print(lr.coef_) # 회귀 계수

Index(['diagonal', 'height_left', 'height_right', 'margin_low', 'margin_up',
       'length'],
      dtype='object')
[[ 0.19354751 -0.32751962 -0.82972784 -2.68915546 -1.72035892  3.2545774 ]]


In [34]:
example = [[171, 104, 104, 5, 3, 113]]
if lr.predict(example) == True:
  print("It's real money!")
else:
  print("It's fake!")

print(lr.predict_proba(example))

It's real money!
[[0. 1.]]


In [35]:
# 모델 평가하기
# confusion_matrix
cmtx = pd.DataFrame(confusion_matrix(y_test, y_pred), index = ['P', 'N'], columns = ['T', 'N'])
cmtx

T    N
P  127    0
N    0  239

In [36]:
# accuracy
accuracy_score(y_test, y_pred)

1.0

In [37]:
# precision, recall, f_score
precision_recall_fscore_support(y_test, y_pred, average='binary')

(1.0, 1.0, 1.0, None)

#### logistic regression 직접 구현

In [38]:
# 데이터 준비 - titaanic dataset
!kaggle datasets download -d moro146/titaanic-dataset-for-logistic-regression

  0% 0.00/4.85k [00:00<?, ?B/s]
100% 4.85k/4.85k [00:00<00:00, 8.64MB/s]


In [39]:
!unzip titaanic-dataset-for-logistic-regression.zip

Archive:  titaanic-dataset-for-logistic-regression.zip
  inflating: Titaanic Datasetforlogisticregression .csv  


In [79]:
import pandas as pd
import numpy as np
from tqdm import tqdm
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import MinMaxScaler
from sklearn.metrics import confusion_matrix
from sklearn.metrics import accuracy_score
from sklearn.metrics import precision_recall_fscore_support

In [41]:
data = pd.read_csv("./Titaanic Datasetforlogisticregression .csv")
data.head()

Survived  Pclass     Sex   Age  Siblings/Spouses Aboard  \
0         0       3    male  22.0                        1   
1         1       1  female  38.0                        1   
2         1       3  female  26.0                        0   
3         1       1  female  35.0                        1   
4         0       3    male  35.0                        0   

   Parents/Children Aboard     Fare  
0                        0   7.2500  
1                        0  71.2833  
2                        0   7.9250  
3                        0  53.1000  
4                        0   8.0500

In [42]:
# 결측값 확인
data.isna().sum()

Survived                   0
Pclass                     0
Sex                        0
Age                        0
Siblings/Spouses Aboard    0
Parents/Children Aboard    0
Fare                       0
dtype: int64

In [43]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 887 entries, 0 to 886
Data columns (total 7 columns):
 #   Column                   Non-Null Count  Dtype  
---  ------                   --------------  -----  
 0   Survived                 887 non-null    int64  
 1   Pclass                   887 non-null    int64  
 2   Sex                      887 non-null    object 
 3   Age                      887 non-null    float64
 4   Siblings/Spouses Aboard  887 non-null    int64  
 5   Parents/Children Aboard  887 non-null    int64  
 6   Fare                     887 non-null    float64
dtypes: float64(2), int64(4), object(1)
memory usage: 48.6+ KB


In [44]:
# 라벨 인코딩
def label_encoder(df: pd.DataFrame) -> pd.DataFrame:
  for col in df.columns:
      label = {}
      if df[col].dtype == "object":
        for i, value in enumerate(df[col].unique()):
          label[value] = i
        df[col] = df[col].map(lambda x: label[x])
  return df

data = label_encoder(data)
data.head()

Survived  Pclass  Sex   Age  Siblings/Spouses Aboard  \
0         0       3    0  22.0                        1   
1         1       1    1  38.0                        1   
2         1       3    1  26.0                        0   
3         1       1    1  35.0                        1   
4         0       3    0  35.0                        0   

   Parents/Children Aboard     Fare  
0                        0   7.2500  
1                        0  71.2833  
2                        0   7.9250  
3                        0  53.1000  
4                        0   8.0500

In [45]:
X_data = data.drop(['Survived'], axis=1)
target = data['Survived']

In [46]:
# 데이터 정규화
mms = MinMaxScaler()
cols = ["Age", "Siblings/Spouses Aboard", "Parents/Children Aboard", "Fare"]
X_data[cols] = mms.fit_transform(X_data[cols])
X_data.head()

Pclass  Sex       Age  Siblings/Spouses Aboard  Parents/Children Aboard  \
0       3    0  0.271174                    0.125                      0.0   
1       1    1  0.472229                    0.125                      0.0   
2       3    1  0.321438                    0.000                      0.0   
3       1    1  0.434531                    0.125                      0.0   
4       3    0  0.434531                    0.000                      0.0   

       Fare  
0  0.014151  
1  0.139136  
2  0.015469  
3  0.103644  
4  0.015713

In [47]:
# 데이터 분리
X_train, X_test, y_train, y_test = train_test_split(X_data, target)

In [80]:
class LogisticRegression():
  def __init__(self, learning_rate=0.01, epoch=100000):
    self._learning_rate = learning_rate
    self._epoch = epoch

  # sigmoid func
  def sigmoid(self, z):
      return 1.0 / (1.0 + np.exp(-z))

  # cross entropy func
  def loss(self, h, y):
    delta = 1e-7
    return -np.sum(y * np.log(h + delta)) / len(h)

  def fit(self, X, y):
    sample_len, feature_len = np.shape(X)

    self._W = np.zeros(feature_len)

    for i in tqdm(range(self._epoch)):
      z = np.dot(X, self._W)
      h = self.sigmoid(z)

      residual = h - y

      loss = self.loss(h, y)
      gradient = np.dot(X.transpose(), residual) / sample_len

      self._W -= gradient * self._learning_rate

  def predict_proba(self, X):
    return self.sigmoid(np.dot(X, self._W))

  def predict(self, X):
    return self.predict_proba(X).round()

In [83]:
model = LogisticRegression()

In [84]:
model.fit(X_train, y_train)

100%|██████████| 100000/100000 [02:16<00:00, 730.66it/s]


In [85]:
model.predict_proba(X_test)

array([0.69196078, 0.64421878, 0.20522293, 0.20987207, 0.76635672,
       0.95715137, 0.74071197, 0.12044169, 0.58481231, 0.12618218,
       0.9573997 , 0.12444307, 0.12381728, 0.89669297, 0.86364264,
       0.79258469, 0.65701804, 0.09774856, 0.11867442, 0.11146375,
       0.28689664, 0.12391848, 0.64110931, 0.11593721, 0.16120834,
       0.21851391, 0.95341676, 0.12628394, 0.90713494, 0.2002276 ,
       0.10855219, 0.8068871 , 0.18102714, 0.70155912, 0.20172023,
       0.70256553, 0.69927185, 0.62926599, 0.05262644, 0.25823877,
       0.80650618, 0.12149266, 0.12359409, 0.57134774, 0.67700721,
       0.22690475, 0.80163212, 0.11374032, 0.42335915, 0.09775641,
       0.1052256 , 0.68616057, 0.62820147, 0.62436471, 0.12265077,
       0.11247625, 0.12694966, 0.61987406, 0.40655266, 0.09417046,
       0.69412436, 0.09416232, 0.87512735, 0.26870584, 0.12106485,
       0.16779296, 0.12222225, 0.12254085, 0.12049386, 0.08779241,
       0.11258081, 0.92228997, 0.12971862, 0.11719747, 0.29016

In [87]:
y_pred = model.predict(X_test)
y_pred

array([1., 1., 0., 0., 1., 1., 1., 0., 1., 0., 1., 0., 0., 1., 1., 1., 1.,
       0., 0., 0., 0., 0., 1., 0., 0., 0., 1., 0., 1., 0., 0., 1., 0., 1.,
       0., 1., 1., 1., 0., 0., 1., 0., 0., 1., 1., 0., 1., 0., 0., 0., 0.,
       1., 1., 1., 0., 0., 0., 1., 0., 0., 1., 0., 1., 0., 0., 0., 0., 0.,
       0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 1., 1., 0., 0., 0.,
       0., 1., 0., 0., 0., 1., 1., 1., 0., 0., 0., 0., 0., 0., 0., 1., 0.,
       0., 1., 0., 0., 0., 0., 1., 1., 1., 0., 1., 1., 0., 0., 0., 0., 1.,
       1., 0., 0., 1., 1., 0., 0., 0., 1., 1., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 1., 1., 1., 0., 0., 1., 0., 0., 1., 1., 0., 0., 0., 0., 0.,
       0., 1., 0., 0., 0., 0., 1., 0., 1., 1., 1., 1., 0., 1., 0., 1., 1.,
       0., 1., 0., 0., 0., 1., 0., 0., 1., 1., 0., 0., 0., 0., 1., 0., 0.,
       0., 0., 0., 0., 0., 1., 0., 0., 1., 1., 1., 1., 1., 0., 0., 1., 0.,
       0., 0., 0., 0., 1., 1., 1., 1., 0., 0., 0., 0., 0., 1., 0., 0., 1.,
       0.])

In [88]:
# 모델 평가
# Confusion matrix
cm = confusion_matrix(y_test, y_pred)
cm

array([[116,  22],
       [ 24,  60]])

In [89]:
# 정확도
accuracy = accuracy_score(y_test, y_pred)
accuracy

0.7927927927927928

In [91]:
# 정밀도, 재현율, F-score
precision_recall_fscore_support(y_test, y_pred, average='binary')

(0.7317073170731707, 0.7142857142857143, 0.7228915662650603, None)