<a href="https://colab.research.google.com/github/Pheol9166/AIstudy/blob/main/ML/RNN.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

### Preparing Data

In [4]:
!kaggle datasets download -d soheiltehranipour/apple-stock-20132018

  0% 0.00/7.40k [00:00<?, ?B/s]
100% 7.40k/7.40k [00:00<00:00, 19.3MB/s]


In [5]:
!unzip apple-stock-20132018.zip

Archive:  apple-stock-20132018.zip
  inflating: AAPL - Jan2018.xls      
  inflating: AAPL.xls                


### Preprocessing

In [7]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler

In [8]:
data = pd.read_csv("./AAPL.xls")
data = data['Open']
data.head()

0    79.117142
1    78.268570
2    76.709999
3    74.571426
4    75.601425
Name: Open, dtype: float64

In [9]:
data.shape

(1259,)

In [10]:
data = data.values

In [11]:
data

array([ 79.117142,  78.26857 ,  76.709999, ..., 170.100006, 171.      ,
       170.520004])

In [13]:
data = data.reshape(-1, 1)
data

array([[ 79.117142],
       [ 78.26857 ],
       [ 76.709999],
       ...,
       [170.100006],
       [171.      ],
       [170.520004]])

In [14]:
scaler = StandardScaler()
scaled_data = scaler.fit_transform(data)

In [19]:
X = scaled_data[:-1]
X

array([[-0.93981429],
       [-0.96846431],
       [-1.02108575],
       ...,
       [ 2.15563941],
       [ 2.13200568],
       [ 2.16239184]])

In [18]:
y = scaled_data[1:]
y

array([[-0.96846431],
       [-1.02108575],
       [-1.09328958],
       ...,
       [ 2.13200568],
       [ 2.16239184],
       [ 2.14618591]])

In [20]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

In [21]:
X_train = X_train.reshape(X_train.shape[0], X_train.shape[1], 1)
y_train = y_train.reshape(y_train.shape[0], y_train.shape[1], 1)
X_test = X_test.reshape(X_test.shape[0], X_test.shape[1], 1)
y_test = y_test.reshape(y_test.shape[0], y_test.shape[1], 1)

In [23]:
print(f"X_train: \n {X_train[:5]}")
print(f"y_test: \n {y_test[:5]}")

X_train: 
 [[[ 1.62117705]]

 [[-1.19559026]]

 [[ 1.34769962]]

 [[ 1.74373554]]

 [[-0.38871175]]]
y_test: 
 [[[ 0.59479333]]

 [[-1.46154315]]

 [[-1.39474137]]

 [[-1.56355458]]

 [[ 1.24168502]]]


### SimpleRNN

In [43]:
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import SimpleRNN, Dense
from sklearn.metrics import mean_squared_error

In [35]:
model = Sequential()
model.add(SimpleRNN(32))
model.add(Dense(1, activation='linear'))

In [36]:
model.compile(optimizer='adam', loss='mse')

In [37]:
model.fit(X_train, y_train, epochs=10, verbose=1)

Epoch 1/10
32/32 [==============================] - 2s 4ms/step - loss: 0.3837
Epoch 2/10
32/32 [==============================] - 0s 4ms/step - loss: 0.0897
Epoch 3/10
32/32 [==============================] - 0s 4ms/step - loss: 0.0141
Epoch 4/10
32/32 [==============================] - 0s 4ms/step - loss: 0.0067
Epoch 5/10
32/32 [==============================] - 0s 4ms/step - loss: 0.0065
Epoch 6/10
32/32 [==============================] - 0s 4ms/step - loss: 0.0064
Epoch 7/10
32/32 [==============================] - 0s 4ms/step - loss: 0.0063
Epoch 8/10
32/32 [==============================] - 0s 4ms/step - loss: 0.0062
Epoch 9/10
32/32 [==============================] - 0s 4ms/step - loss: 0.0062
Epoch 10/10
32/32 [==============================] - 0s 4ms/step - loss: 0.0061


In [45]:
y_predict = model.predict(X_test)
y_predict[:5]

8/8 [==============================] - 0s 2ms/step


array([[ 0.5873496],
       [-1.4742708],
       [-1.4687333],
       [-1.4979194],
       [ 1.3085005]], dtype=float32)

In [46]:
y_test[:5]

array([[[ 0.59479333]],

       [[-1.46154315]],

       [[-1.39474137]],

       [[-1.56355458]],

       [[ 1.24168502]]])

In [49]:
# evaluate
mean_squared_error(y_test.reshape(-1), y_predict.reshape(-1))

0.00668632894522213

### LSTM

In [78]:
from tensorflow.keras.layers import LSTM

In [79]:
model = Sequential()
model.add(LSTM(64))
model.add(Dense(1, activation='linear'))

In [80]:
model.compile(optimizer='adam', loss='mse', metrics=['mae'])

In [81]:
model.fit(X_train, y_train, epochs=10, verbose=1)

Epoch 1/10
32/32 [==============================] - 2s 4ms/step - loss: 0.8664 - mae: 0.7462
Epoch 2/10
32/32 [==============================] - 0s 4ms/step - loss: 0.6457 - mae: 0.6444
Epoch 3/10
32/32 [==============================] - 0s 4ms/step - loss: 0.4253 - mae: 0.5220
Epoch 4/10
32/32 [==============================] - 0s 4ms/step - loss: 0.2255 - mae: 0.3775
Epoch 5/10
32/32 [==============================] - 0s 4ms/step - loss: 0.0844 - mae: 0.2285
Epoch 6/10
32/32 [==============================] - 0s 4ms/step - loss: 0.0213 - mae: 0.1121
Epoch 7/10
32/32 [==============================] - 0s 4ms/step - loss: 0.0066 - mae: 0.0602
Epoch 8/10
32/32 [==============================] - 0s 4ms/step - loss: 0.0047 - mae: 0.0510
Epoch 9/10
32/32 [==============================] - 0s 4ms/step - loss: 0.0042 - mae: 0.0479
Epoch 10/10
32/32 [==============================] - 0s 4ms/step - loss: 0.0040 - mae: 0.0462


In [82]:
y_predict = model.predict(X_test)
y_predict[:5]

8/8 [==============================] - 0s 2ms/step


array([[ 0.5463721],
       [-1.4433475],
       [-1.437593 ],
       [-1.4679893],
       [ 1.2957821]], dtype=float32)

In [83]:
y_test[:5]

array([[[ 0.59479333]],

       [[-1.46154315]],

       [[-1.39474137]],

       [[-1.56355458]],

       [[ 1.24168502]]])

In [84]:
# evaluate
mean_squared_error(y_test.reshape(-1), y_predict.reshape(-1))

0.004988342293125201

### Bidirectional LSTM

In [85]:
from tensorflow.keras.layers import Bidirectional

In [86]:
model = Sequential()
model.add(Bidirectional(LSTM(64)))
model.add(Dense(1, activation='linear'))

In [87]:
model.compile(optimizer='adam', loss='mse', metrics=['mae'])

In [88]:
model.fit(X_train, y_train, epochs=10, verbose=1)

Epoch 1/10
32/32 [==============================] - 4s 5ms/step - loss: 0.7241 - mae: 0.6824
Epoch 2/10
32/32 [==============================] - 0s 5ms/step - loss: 0.4018 - mae: 0.5060
Epoch 3/10
32/32 [==============================] - 0s 5ms/step - loss: 0.1529 - mae: 0.3081
Epoch 4/10
32/32 [==============================] - 0s 5ms/step - loss: 0.0298 - mae: 0.1323
Epoch 5/10
32/32 [==============================] - 0s 5ms/step - loss: 0.0051 - mae: 0.0538
Epoch 6/10
32/32 [==============================] - 0s 5ms/step - loss: 0.0039 - mae: 0.0455
Epoch 7/10
32/32 [==============================] - 0s 5ms/step - loss: 0.0037 - mae: 0.0433
Epoch 8/10
32/32 [==============================] - 0s 5ms/step - loss: 0.0036 - mae: 0.0423
Epoch 9/10
32/32 [==============================] - 0s 5ms/step - loss: 0.0035 - mae: 0.0419
Epoch 10/10
32/32 [==============================] - 0s 5ms/step - loss: 0.0035 - mae: 0.0420


In [89]:
y_predict = model.predict(X_test)
y_predict[:5]

8/8 [==============================] - 1s 3ms/step


array([[ 0.5532964],
       [-1.4605274],
       [-1.454261 ],
       [-1.487412 ],
       [ 1.2934643]], dtype=float32)

In [90]:
y_test[:5]

array([[[ 0.59479333]],

       [[-1.46154315]],

       [[-1.39474137]],

       [[-1.56355458]],

       [[ 1.24168502]]])

In [91]:
# evaluate
mean_squared_error(y_test.reshape(-1), y_predict.reshape(-1))

0.004388098933320605