<a href="https://colab.research.google.com/github/Pheol9166/AIstudy/blob/main/ML/RNN.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

### Preparing Data

In [1]:
!kaggle datasets download -d soheiltehranipour/apple-stock-20132018

apple-stock-20132018.zip: Skipping, found more recently modified local copy (use --force to force download)


In [2]:
!unzip apple-stock-20132018.zip

Archive:  apple-stock-20132018.zip
replace AAPL - Jan2018.xls? [y]es, [n]o, [A]ll, [N]one, [r]ename: y
  inflating: AAPL - Jan2018.xls      
replace AAPL.xls? [y]es, [n]o, [A]ll, [N]one, [r]ename: y
  inflating: AAPL.xls                


### Preprocessing

In [3]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler

In [4]:
data = pd.read_csv("./AAPL.xls")
data = data['Open']
data.head()

0    79.117142
1    78.268570
2    76.709999
3    74.571426
4    75.601425
Name: Open, dtype: float64

In [5]:
data.shape

(1259,)

In [6]:
data = data.values

In [7]:
data

array([ 79.117142,  78.26857 ,  76.709999, ..., 170.100006, 171.      ,
       170.520004])

In [8]:
data = data.reshape(-1, 1)
data

array([[ 79.117142],
       [ 78.26857 ],
       [ 76.709999],
       ...,
       [170.100006],
       [171.      ],
       [170.520004]])

In [9]:
scaler = StandardScaler()
scaled_data = scaler.fit_transform(data)

In [10]:
X = scaled_data[:-1]
X

array([[-0.93981429],
       [-0.96846431],
       [-1.02108575],
       ...,
       [ 2.15563941],
       [ 2.13200568],
       [ 2.16239184]])

In [11]:
y = scaled_data[1:]
y

array([[-0.96846431],
       [-1.02108575],
       [-1.09328958],
       ...,
       [ 2.13200568],
       [ 2.16239184],
       [ 2.14618591]])

In [12]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

In [13]:
X_train = X_train.reshape(X_train.shape[0], X_train.shape[1], 1)
y_train = y_train.reshape(y_train.shape[0], y_train.shape[1], 1)
X_test = X_test.reshape(X_test.shape[0], X_test.shape[1], 1)
y_test = y_test.reshape(y_test.shape[0], y_test.shape[1], 1)

In [14]:
print(f"X_train: \n {X_train[:5]}")
print(f"y_test: \n {y_test[:5]}")

X_train: 
 [[[ 1.62117705]]

 [[-1.19559026]]

 [[ 1.34769962]]

 [[ 1.74373554]]

 [[-0.38871175]]]
y_test: 
 [[[ 0.59479333]]

 [[-1.46154315]]

 [[-1.39474137]]

 [[-1.56355458]]

 [[ 1.24168502]]]


### SimpleRNN

In [15]:
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import SimpleRNN, Dense
from sklearn.metrics import mean_squared_error

In [16]:
model = Sequential()
model.add(SimpleRNN(32))
model.add(Dense(1, activation='linear'))

In [17]:
model.compile(optimizer='adam', loss='mse')

In [18]:
model.fit(X_train, y_train, epochs=10, verbose=1)

Epoch 1/10
32/32 [==============================] - 3s 6ms/step - loss: 1.0220
Epoch 2/10
32/32 [==============================] - 0s 6ms/step - loss: 0.4040
Epoch 3/10
32/32 [==============================] - 0s 6ms/step - loss: 0.1203
Epoch 4/10
32/32 [==============================] - 0s 6ms/step - loss: 0.0268
Epoch 5/10
32/32 [==============================] - 0s 5ms/step - loss: 0.0087
Epoch 6/10
32/32 [==============================] - 0s 5ms/step - loss: 0.0067
Epoch 7/10
32/32 [==============================] - 0s 6ms/step - loss: 0.0066
Epoch 8/10
32/32 [==============================] - 0s 6ms/step - loss: 0.0065
Epoch 9/10
32/32 [==============================] - 0s 6ms/step - loss: 0.0064
Epoch 10/10
32/32 [==============================] - 0s 6ms/step - loss: 0.0064


In [19]:
y_predict = model.predict(X_test)
y_predict[:5]

8/8 [==============================] - 0s 2ms/step


array([[ 0.59064484],
       [-1.4682316 ],
       [-1.4627813 ],
       [-1.4915047 ],
       [ 1.3092575 ]], dtype=float32)

In [20]:
y_test[:5]

array([[[ 0.59479333]],

       [[-1.46154315]],

       [[-1.39474137]],

       [[-1.56355458]],

       [[ 1.24168502]]])

In [21]:
# evaluate
mean_squared_error(y_test.reshape(-1), y_predict.reshape(-1))

0.006875738356987121

### LSTM

In [22]:
from tensorflow.keras.layers import LSTM

In [23]:
model = Sequential()
model.add(LSTM(64))
model.add(Dense(1, activation='linear'))

In [24]:
model.compile(optimizer='adam', loss='mse', metrics=['mae'])

In [25]:
model.fit(X_train, y_train, epochs=10, verbose=1)

Epoch 1/10
32/32 [==============================] - 2s 4ms/step - loss: 0.9253 - mae: 0.7725
Epoch 2/10
32/32 [==============================] - 0s 4ms/step - loss: 0.6941 - mae: 0.6688
Epoch 3/10
32/32 [==============================] - 0s 4ms/step - loss: 0.4672 - mae: 0.5471
Epoch 4/10
32/32 [==============================] - 0s 4ms/step - loss: 0.2551 - mae: 0.4038
Epoch 5/10
32/32 [==============================] - 0s 4ms/step - loss: 0.1037 - mae: 0.2558
Epoch 6/10
32/32 [==============================] - 0s 4ms/step - loss: 0.0297 - mae: 0.1323
Epoch 7/10
32/32 [==============================] - 0s 4ms/step - loss: 0.0086 - mae: 0.0702
Epoch 8/10
32/32 [==============================] - 0s 4ms/step - loss: 0.0051 - mae: 0.0537
Epoch 9/10
32/32 [==============================] - 0s 4ms/step - loss: 0.0044 - mae: 0.0494
Epoch 10/10
32/32 [==============================] - 0s 4ms/step - loss: 0.0041 - mae: 0.0468


In [26]:
y_predict = model.predict(X_test)
y_predict[:5]

8/8 [==============================] - 0s 3ms/step


array([[ 0.5418696],
       [-1.4385679],
       [-1.4328352],
       [-1.4631178],
       [ 1.2947639]], dtype=float32)

In [27]:
y_test[:5]

array([[[ 0.59479333]],

       [[-1.46154315]],

       [[-1.39474137]],

       [[-1.56355458]],

       [[ 1.24168502]]])

In [28]:
# evaluate
mean_squared_error(y_test.reshape(-1), y_predict.reshape(-1))

0.005042314191638854

### Bidirectional LSTM

In [29]:
from tensorflow.keras.layers import Bidirectional

In [30]:
model = Sequential()
model.add(Bidirectional(LSTM(64)))
model.add(Dense(1, activation='linear'))

In [31]:
model.compile(optimizer='adam', loss='mse', metrics=['mae'])

In [32]:
model.fit(X_train, y_train, epochs=10, verbose=1)

Epoch 1/10
32/32 [==============================] - 4s 7ms/step - loss: 0.9384 - mae: 0.7792
Epoch 2/10
32/32 [==============================] - 0s 9ms/step - loss: 0.6003 - mae: 0.6214
Epoch 3/10
32/32 [==============================] - 0s 8ms/step - loss: 0.2998 - mae: 0.4379
Epoch 4/10
32/32 [==============================] - 0s 9ms/step - loss: 0.0913 - mae: 0.2355
Epoch 5/10
32/32 [==============================] - 0s 8ms/step - loss: 0.0141 - mae: 0.0892
Epoch 6/10
32/32 [==============================] - 0s 8ms/step - loss: 0.0044 - mae: 0.0494
Epoch 7/10
32/32 [==============================] - 0s 6ms/step - loss: 0.0039 - mae: 0.0450
Epoch 8/10
32/32 [==============================] - 0s 5ms/step - loss: 0.0036 - mae: 0.0431
Epoch 9/10
32/32 [==============================] - 0s 5ms/step - loss: 0.0036 - mae: 0.0422
Epoch 10/10
32/32 [==============================] - 0s 5ms/step - loss: 0.0035 - mae: 0.0417


In [33]:
y_predict = model.predict(X_test)
y_predict[:5]

8/8 [==============================] - 1s 3ms/step


array([[ 0.54563266],
       [-1.4618454 ],
       [-1.4555904 ],
       [-1.4886851 ],
       [ 1.2861447 ]], dtype=float32)

In [34]:
y_test[:5]

array([[[ 0.59479333]],

       [[-1.46154315]],

       [[-1.39474137]],

       [[-1.56355458]],

       [[ 1.24168502]]])

In [35]:
# evaluate
mean_squared_error(y_test.reshape(-1), y_predict.reshape(-1))

0.004380992009178433

### GRU

In [36]:
from tensorflow.keras.layers import GRU

In [37]:
model = Sequential()
model.add(Bidirectional(GRU(64)))
model.add(Dense(1, activation='linear'))

In [38]:
model.compile(optimizer='adam', loss='mse', metrics=['mae'])

In [39]:
model.fit(X_train, y_train, epochs=10, verbose=1)

Epoch 1/10
32/32 [==============================] - 4s 5ms/step - loss: 0.7161 - mae: 0.6735
Epoch 2/10
32/32 [==============================] - 0s 5ms/step - loss: 0.2336 - mae: 0.3785
Epoch 3/10
32/32 [==============================] - 0s 5ms/step - loss: 0.0334 - mae: 0.1372
Epoch 4/10
32/32 [==============================] - 0s 5ms/step - loss: 0.0040 - mae: 0.0455
Epoch 5/10
32/32 [==============================] - 0s 5ms/step - loss: 0.0036 - mae: 0.0425
Epoch 6/10
32/32 [==============================] - 0s 5ms/step - loss: 0.0035 - mae: 0.0416
Epoch 7/10
32/32 [==============================] - 0s 5ms/step - loss: 0.0035 - mae: 0.0415
Epoch 8/10
32/32 [==============================] - 0s 5ms/step - loss: 0.0034 - mae: 0.0411
Epoch 9/10
32/32 [==============================] - 0s 5ms/step - loss: 0.0034 - mae: 0.0408
Epoch 10/10
32/32 [==============================] - 0s 5ms/step - loss: 0.0034 - mae: 0.0407


In [40]:
y_predict = model.predict(X_test)
y_predict[:5]

8/8 [==============================] - 1s 3ms/step


array([[ 0.538057 ],
       [-1.4732269],
       [-1.466814 ],
       [-1.5007603],
       [ 1.2763023]], dtype=float32)

In [41]:
y_test[:5]

array([[[ 0.59479333]],

       [[-1.46154315]],

       [[-1.39474137]],

       [[-1.56355458]],

       [[ 1.24168502]]])

In [42]:
# evaluate
mean_squared_error(y_test.reshape(-1), y_predict.reshape(-1))

0.004309615606519392